name: pokedex
description: "Pokedex"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #cache image
  cached_network_image: ^3.3.0

  #service
  http: ^1.1.2

  #state_managment
  get: ^4.6.6

  #lottie
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/png/